# Generated by Django 5.1.2 on 2024-10-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_role',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user_role',
            old_name='user_id',
            new_name='user',
        ),
    ]
