# Generated by Django 5.1.3 on 2024-11-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_role_id_user_role_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
