# Generated by Django 5.1.3 on 2024-11-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_posts_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='post',
        ),
        migrations.RenameModel(
            old_name='roles',
            new_name='role',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
