# Generated by Django 5.1.3 on 2024-11-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_posts_post_rename_roles_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
    ]
