# Generated by Django 5.1.3 on 2024-11-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_post_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=18, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='user',
        ),
        migrations.DeleteModel(
            name='role',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='user_role',
        ),
    ]
