# Generated by Django 5.1.3 on 2024-11-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_newuser_delete_post_remove_user_role_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Usuario', 'Usuario')], default='Usuario', max_length=10),
        ),
    ]
