# Generated by Django 5.1.3 on 2024-11-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_newuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
