# Generated by Django 5.1.3 on 2024-11-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_newuser_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUser',
            new_name='NewUser1',
        ),
    ]
