# Generated by Django 5.1.3 on 2024-11-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_newuser_newuser1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUser1',
            new_name='NewUser',
        ),
    ]
